### ISSUE TITLE
[Documentation] System-Architektur (mit C4-Methode) und textuelle Beschreibung erstellen

### ISSUE THREAD

**Issue by MK2112** [HWR-Berlin-SWE-II-Gruppe-2-Team-3-2022/Dokumentation#18]
## Detailed Description
Abbildung der System-Architektur (mit C4-Methode) und textuelle Beschreibung dazu (200-250 Wörter), Abgabe einer Datei im PDF-Format (5+5 / 100 Punkte)

**Comment by dashvogel** [comment]
[Equaly_C4_v1.pdf](https://github.com/HWR-Berlin-SWE-II-Gruppe-2-Team-3-2022/Dokumentation/files/8104284/Equaly_C4_v1.pdf)

sorry weiß net wie man ne review requestet.

Anyway, das ist so die erste Version die ich dem Text entnehmen konnte.
Sagt mir alles, was daran falsch ist. :D

**Comment by MK2112** [comment]
HTML-Frontend:
- View durch HTML-Frontend ersetzen (das ist die View)
- Datatransfer (finished gendered text) -> Datatransfer (gendered text suggestion)

Am besten das HTML-Frontend so darstellen, wie in https://c4model.com/img/bigbankplc-Containers.png die "Single Page Application" dargestellt ist.

POS-Tagger:
- [Container: OpenNLP] -> [Container: Java, OpenNLP]

Language-Trigger:
- "Language-Trigger" -> "Language-Tagger"
- [Container: Linuga] -> [Container: Java, Linuga]

Language Tagger macht keinen Datatransfer an eine andere Komponente. Das macht nur der Controller. Der erhält jeweils die Zwischenergebnisse und "kontrolliert" die Weiterverteilung / versendet die Zwischenergebnisse je von Language-Tagger, Tokenizer und POS-Tagger

EqualyController erhält vom Substituter die "gendered text suggestion" suggestion zurück

Substituter:
- Datatransfer (Token-Dataset with needed substitutions) -> Datatransfer (Token-Dataset requiring substitutions of nouns), dann response für diese "noun substitution", diesen kreislauf nochmal für "substitutions of articles"

Database:
- versendet "substitution suggestions for articles and nouns"
